version: "3"
services:

    data:
      container_name: rpi-python-bottle-data
      image: hypriot/armhf-busybox
      stdin_open: true
      tty: false
      volumes:
        - ./docker/mysql:/etc/mysql/conf.d:ro
        - ./app:/home/bottle
      command: /bin/sh

    mysql:
      container_name: rpi-python-bottle-db
      image: hypriot/rpi-mysql
      volumes:
       - ./initdb.d:/docker-entrypoint-initdb.d
      environment:
        MYSQL_ROOT_PASSWORD: password
        MYSQL_USER: bottle
        MYSQL_PASSWORD: bottle
        MYSQL_DATABASE: measurement
      ports:
        - "3306:3306"
      volumes_from:
        - data

    application:
      container_name: rpi-python-bottle-app-server
      build: .
      tty: false
      volumes_from:
        - data
      volumes:
       - ./app_server:/home/bottle/app
      ports:
        - "8080:8080"
      environment:
        CODEIGNITER_ENV: development
        
    application:
      container_name: rpi-python-bottle-app-measure
      build: .
      tty: false
      volumes:
       - ./app_measure:/home/bottle/app
      environment:
        CODEIGNITER_ENV: development

