version: "3"

volumes:
  mysql-db:
    driver_opts:
      type: none
      device: /mnt/nas/workspace/data/mysql
      o: bind
      
services:

    mysql:
      container_name: rpi-python-bottle-db
      image: hypriot/rpi-mysql
      volumes:
       - ./sql:/docker-entrypoint-initdb.d
       - mysql-db:/var/lib/mysql
       - ./docker/mysql:/etc/mysql/conf.d:ro
      environment:
        MYSQL_ROOT_PASSWORD: password
        MYSQL_USER: bottle
        MYSQL_PASSWORD: bottle
        MYSQL_DATABASE: instantaneous_measurement
      ports:
        - "3306:3306"


    server-application:
      container_name: rpi-python-bottle-app-server
      build: .
      tty: false
      volumes:
       - ./app_server:/home/bottle/app
      ports:
        - "8080:8080"
      environment:
        CODEIGNITER_ENV: development
      entrypoint:
       - /usr/local/bin/python3
       - /home/bottle/app/server.py
       
        
    measure-application:
      container_name: rpi-python-bottle-app-measure
      build: .
      tty: false
      volumes:
       - ./app_measure:/home/bottle/app
      environment:
        CODEIGNITER_ENV: development
      devices:
       - "/dev/ttyUSB0:/dev/ttyUSB0:rwm"
      entrypoint:
       - /usr/local/bin/python3
       - /home/bottle/app/get-power.py
      cap_add:
       - SYS_RAWIO

