   
services:
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      app_net:
        ipv4_address: 172.19.0.5

  measure-application:
      container_name: rpi-python-bottle-app-measure
      image: kenonemorita/rpi-python-bottle-app-measure
      build: ./app_measure
      depends_on:
        - redis
      tty: false
      volumes:
       - ./app_measure:/home/bottle/app
      environment:
        CODEIGNITER_ENV: development
      devices:
       - "/dev/ttyUSB0:/dev/ttyUSB0:rwm"
      entrypoint:
       - /usr/local/bin/python3
       - /home/bottle/app/get-power.py
      privileged: true
      cap_add:
       - SYS_RAWIO
      networks:
        app_net:
          ipv4_address: 172.19.0.10

      logging:
        driver: "json-file" # defaults if not specified
        options:
          max-size: "10m"
          max-file: "5"
      restart: always

  my_flask_app:
      build:
        context: ./my_flask_app
      container_name: my_flask_app
      depends_on:
        - redis
      ports:
        - "5000:5000"  # Flask用のポートを公開
      networks:
        app_net:
          ipv4_address: 172.19.0.15  # 固定IPアドレスを割り当てる

networks:
  app_net:
    driver: bridge
    ipam:
     driver: default
     config:
       - subnet: 172.19.0.0/16

